[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
soddle = "8buzRBsMxWpYvLpxqSNogsdP7reUGRNFR8EEUkZZ9c33"

[programs.mainnet]
soddle = "8buzRBsMxWpYvLpxqSNogsdP7reUGRNFR8EEUkZZ9c33"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
cluster = "https://devnet.sonic.game"

#wallet = "~/.config/solana/id.json"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
