[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
soddle = "CZ4bJsRfjT7vsQpi6dGenbyP1JksLVs82zM68ReiNv43"

[programs.mainnet]
soddle = "2Hs7uqUsAZH8xXbKBHfDThiTCWh1J5Ff9oUNKzM123Gz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
