[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
soddle = "9b4J9BTbBnKfrfZ7YC1WpArk1z9DgQuTEhWJtoBshz7w"

[programs.mainnet]
soddle = "9b4J9BTbBnKfrfZ7YC1WpArk1z9DgQuTEhWJtoBshz7w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
